<a href="https://colab.research.google.com/github/kbhavre/Asol-Dhaba/blob/master/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calculating the time taken by list

In [4]:
import numpy as np
from time import process_time

list1= [i for i in range(10000)]
start_time = process_time()
list1 = [i+5 for i in range(10000)]
end_time = process_time()
print("Time for list = ",end_time - start_time)

Time for list =  0.001801754999999794


Calculating the time taken by Numpy Arrays

In [5]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print("Numpy array time = ", end_time-start_time)

Numpy array time =  0.0003951759999996085


**Creating Arrays**

In [11]:
# This is how we normally create a list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

# Creating an numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1)
type(arr1)



[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

**Creating Multi dimensional arrays**

In [17]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)

b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

c= np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)
print(c.shape)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
(2, 4)


**Initial placeholders in Numpy Arrays**

In [22]:
x = np.zeros((4,5))
print(x)

y= np.ones((3,4))
print(y)

# For arrays of particular values
z= np.full((5,4), 5)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


**Printing Identity Matrix**

In [24]:
# 4X4 matrix
a = np.eye(4)
print(a)

# 3X3 matrix
b= np.eye(3)
print(b)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Creating arrays with random values**

In [33]:
# random values between 0 and 1
a = np.random.random((3,4))
print(a)

# within a specific range
b = np.random.randint(1,100,(3,5))
print(b)

# Arrays of evenly spaced values, based on values
c = np.linspace(10,30, 5)
print(c)

# evenly spaced , based on step
d= np.arange(10,30, 5)
print(d)

[[0.35092562 0.23051111 0.87941544 0.17183649]
 [0.30941302 0.70894755 0.90260286 0.10854135]
 [0.1123097  0.7741937  0.70452573 0.91818337]]
[[64 98 84 44 67]
 [77 95 15 99 36]
 [55 53 41 96 24]]
[10. 15. 20. 25. 30.]
[10 15 20 25]


**ANALYSING A NUMPY ARRAY**

In [42]:
a = np.random.randint(1,90, (5,5))
print(a)


# array dimension
print(a.shape)

# No of dimension
print(a.ndim)

# No. of elements in array
print(a.size)

# Checking data type of the values present
print(a.dtype)

[[57 17 50 13 44]
 [76 89 83 36 34]
 [12 86 55 37 44]
 [63 37 28 76 48]
 [36 42 58 85 77]]
(5, 5)
2
25
int64


**Mathematical Operations**

In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)

# we can also use functions
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[9 9 7]
 [3 2 3]
 [1 6 6]]
[[13 16 11]
 [17 18 18]
 [15 14 10]]
[[22 25 18]
 [20 20 21]
 [16 20 16]]
[[ -4  -7  -4]
 [-14 -16 -15]
 [-14  -8  -4]]
[[117 144  77]
 [ 51  36  54]
 [ 15  84  60]]
[[0.69230769 0.5625     0.63636364]
 [0.17647059 0.11111111 0.16666667]
 [0.06666667 0.42857143 0.6       ]]


**Array Manipulation**

In [53]:
a = np.random.randint(0,10, (3,3))
print(a)
print(a.shape)

# Transpose a matrix
trans = np.transpose(a)
print(trans)
print(trans.shape)

# Another way of transposing
trans2 = a.T
print(trans2)
print(trans2.shape)

# Reshaping an array (Imp)
b = np.random.randint(0,10, (2,3))
print(b)
print(b.shape)

c = b.reshape(3,2)
print(c)
print(c.shape)

[[4 3 1]
 [5 0 4]
 [5 3 8]]
(3, 3)
[[4 5 5]
 [3 0 3]
 [1 4 8]]
(3, 3)
[[4 5 5]
 [3 0 3]
 [1 4 8]]
(3, 3)
[[1 1 9]
 [4 8 8]]
(2, 3)
[[1 1]
 [9 4]
 [8 8]]
(3, 2)
